post:
    description: Authenticate user
    body:
      application/json:
        type: object
        properties:
          email: string
          password: string
        example: !include requests/post.json
    responses:
      200:
        description: Successfully authenticated user.
        body:
          application/json:
            type: object
            properties:
              token: string
              user: object
            example: !include responses/post.json
      400:
        description: Wrong password sent.
        body:
          application/json:
            type: Error
            example: {
              message: "Wrong password",
              error: {
                message: "Wrong password",
                status: 400
              }
            }
      404:
        body:
          application/json:
            type: Error
            example: !include ../../common/errors/userNotFound.json
